version: '3.8'
services:
  kong-database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    networks:
      - kong-net
    volumes:
      - kong-db:/var/lib/postgresql/data

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    networks:
      - kong-net
    depends_on:
      - kong-database
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"

  keycloak:
    # Configuration for Keycloak would go here

  backend-api:
    build:
      context: ./packages/backend-api
      dockerfile: Dockerfile
    networks:
      - backend-net
    depends_on:
      - keycloak
      - kong-database
    environment:
      - DATABASE_URI=mongodb://mongo:27017/tasks

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    networks:
      - frontend-net
    depends_on:
      - backend-api
    ports:
      - "3000:3000"

  # Add configuration for the MongoDB or another database if required

networks:
  kong-net:
  backend-net:
  frontend-net:

volumes:
  kong-db:

# Note: You will need to add additional configurations for Keycloak, MongoDB, and possibly other services.




services:
  # ... other services ...
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /path/to/your/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend-api
    networks:
      - frontend-net

# ... networks and volumes ...
